import { PAPER } from "./notebookli";

/** Contextual definitions for every word in this short, fixed research excerpt. */
export const READER_TEXT = {
  before: "To study the interaction of human pathogenic strains with our immune system, ",
  method: "we engineered an mRFP fluorescent protein into these strains",
  after: " using the pCT74 plasmid and protoplast-mediated fungal transformation.",
  result: "Confocal microscopy shows red fluorescence in the transformed MRL8996 strain",
  conclusion: " alongside the Fo47-RFP positive control; gel electrophoresis confirms HygR and mRFP bands at the expected sizes.",
};

export const GLOSSARY: Record<string, string> = {
  ...Object.fromEntries(PAPER.terms.map(({term, definition}) => [term.toLowerCase(), definition])),
  mrfp: "Monomeric red fluorescent protein: a glowing red tag that lets researchers see and track cells under a microscope.",
  protoplast: "A cell whose rigid outer wall has been removed, helping introduced DNA enter.",
  rfp: "Red fluorescent protein: a protein used to make tagged cells visible under suitable light.",
  transformation: "Introducing new genetic material into a cell. Here, it gives fungal cells a fluorescent tag.",
  human: "Relating to people. Here, it identifies fungal strains associated with human infection.",
  strains: "Genetically distinct variants within a species.",
  strain: "A genetically distinct variant within a species.",
  fusarium: "A genus of fungi that includes species capable of infecting plants and people.",
  oxysporum: "The species name in Fusarium oxysporum, the fungus studied here.",
  study: "Investigate something systematically to understand how it works.",
  interaction: "The way two things affect one another; here, fungal cells and the immune system.",
  pathogenic: "Capable of causing disease.",
  immune: "Relating to the body's defenses against infection.",
  system: "A group of parts that work together. The immune system helps defend the body against infection.",
  engineered: "Deliberately modified. Here, the researchers introduced a gene for a fluorescent protein.",
  fluorescent: "Able to absorb light and emit light at a different wavelength.",
  protein: "A molecule made of amino acids. This one produces a red fluorescent signal.",
  pct74: "The named plasmid used to carry genetic material into the fungal cells in this experiment.",
  plasmid: "A DNA molecule used here as a carrier for introducing genes into cells.",
  "protoplast-mediated": "Carried out using cells whose rigid cell walls have been removed, helping new DNA enter.",
  fungal: "Relating to fungi, the group of organisms that includes molds, mushrooms, and yeasts.",
  confocal: "Describing microscopy that rejects out-of-focus light to produce a clearer image of one focal plane.",
  microscopy: "Using a microscope to examine things too small to see clearly with the unaided eye.",
  shows: "Makes visible or provides evidence of something.",
  red: "The color of the fluorescent signal produced by the tag in this experiment.",
  fluorescence: "Light emitted by a substance after it absorbs light; here, the signal makes tagged cells visible.",
  transformed: "Having taken up introduced genetic material.",
  mrl8996: "The identifier of the fungal strain described in this research excerpt.",
  "fo47-rfp": "The fluorescent reference strain used as a positive control in this experiment.",
  positive: "Here, describing a control expected to produce the signal being tested for.",
  control: "A reference used to interpret an experiment. This positive control provides an expected fluorescent signal.",
  gel: "The porous material through which DNA fragments move during gel electrophoresis.",
  electrophoresis: "A technique that uses an electric field to separate charged molecules, such as DNA fragments, in a gel.",
  confirms: "Provides supporting evidence that something is present or correct.",
  hygr: "The hygromycin-resistance marker checked in this experiment.",
  bands: "Visible groups of separated DNA fragments in a gel, used to assess their approximate sizes.",
  expected: "Predicted from what is known about the experiment.",
  sizes: "Here, the lengths of the DNA fragments detected in the gel.",
  to: "Introduces a purpose here: the researchers did this in order to study the interaction.",
  the: "Points to a particular thing already identified by the surrounding words.",
  of: "Connects something with what it belongs to or describes.",
  with: "Together with, or in relation to, something else.",
  our: "Belonging to or associated with us; here, the human immune system.",
  we: "The researchers carrying out this study.",
  an: "Introduces one member of a category, before a vowel sound.",
  into: "Indicates movement or introduction to the inside of something.",
  these: "Refers to the particular strains just mentioned.",
  using: "By means of a particular tool or method.",
  and: "Joins related words or statements.",
  in: "Within or inside something.",
  alongside: "Together with or compared with; here, compared with the positive control.",
  at: "Specifies the point or value being described; here, the predicted DNA fragment lengths.",
};

export function normalizeWord(word: string) {
  return word.toLowerCase().replace(/^[^a-z0-9]+|[^a-z0-9]+$/g, "");
}
